version: "3.9"

services:
  devopsdb:
    image: vaishnavidhulipala04/myrepository:db
    ports:
      - "3306:3306"

  application:
    image: vaishnavidhulipala04/myrepository:db
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb
